spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-lothstar.c144gicsebz1.ap-southeast-2.rds.amazonaws.com:3306/dev_clothstar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: star010101

mybatis:
  mapper-locations: classpath:/mappers/**.xml