#default 공통설정
#  jpa:
#    show-sql: true
#    properties:
#      jdbc:
#        time_zone: Asia/Seoul
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
  sql:
    init:
      mode: always

--- # local
spring:
  config:
    activate:
      on-profile: "db-local"
#  jpa:
#    show-sql: true
#    database-platform: H2
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:localdb
  h2:
    console:
      enabled: true

--- #dev
spring:
  sql:
    init:
      platform: mysql
  config:
    activate:
      on-profile: "db-dev"
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-lothstar.c144gicsebz1.ap-southeast-2.rds.amazonaws.com:3306/dev_clothstar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: star010101